<script src="{{ asset('back-office/assets/js/core/jquery-3.7.1.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/core/popper.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/core/bootstrap.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/jquery-scrollbar/jquery.scrollbar.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/jquery.sparkline/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/webfont/webfont.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/kaiadmin.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/chart.js/chart.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/chart-circle/circles.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/datatables/datatables.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/plugin/bootstrap-notify/bootstrap-notify.min.js') }}"></script>
{{-- <script src="{{ asset('back-office/assets/js/plugin/jsvectormap/jsvectormap.min.js') }}"></script> --}}
{{-- <script src="{{ asset('back-office/assets/js/plugin/jsvectormap/world.js') }}"></script> --}}
<script src="{{ asset('back-office/assets/js/plugin/sweetalert/sweetalert.min.js') }}"></script>
<script src="{{ asset('back-office/assets/js/setting-demo.js') }}"></script>
{{-- <script src="{{ asset('back-office/assets/js/demo.js') }}"></script> --}}
